### ISSUE TITLE
Failed: NameError: uninitialized constant Concerns::Authentication

### ISSUE THREAD

**Issue by nathancolgate** [brandnewbox/oidc_provider#3]
I am trying to generate an ERD diagram for AECOM COLA SAM, but can not. Get the following error.

Not sure what's going on, but it feels like a code smell to me.

@willtcarey - Any thoughts? Low hanging fruit?

```
bash-4.2# bundle exec erd --debug
Loading application in 'src'...
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.6-compliant syntax, but you are running 2.6.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
E, [2021-06-28T20:04:34.689763 #97] ERROR -- : coverage failed to store
E, [2021-06-28T20:04:34.689820 #97] ERROR -- : Coverband Error: #<Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)> Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
W, [2021-06-28T20:04:34.794713 #97]  WARN -- Skylight: [SKYLIGHT] [4.3.1] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
   (0.4ms)  SET  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
  ↳ config/environment.rb:5
   (0.2ms)  use `sam_management`
  ↳ config/environment.rb:5
Creating scope :included. Overwriting existing method BuildingProject.included.
Creating scope :included. Overwriting existing method Site.included.
Creating scope :included. Overwriting existing method Building.included.
Creating scope :included. Overwriting existing method FloorPlan.included.
Creating scope :included. Overwriting existing method BuildingPreassessment.included.
Creating scope :included. Overwriting existing method BuildingSystem.included.
Creating scope :included. Overwriting existing method Deficiency.included.
Creating scope :included. Overwriting existing method Device.included.
Failed: NameError: uninitialized constant Concerns::Authentication
    from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `block in load_missing_constant'
    from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:9:in `without_bootsnap_cache'
    from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `rescue in load_missing_constant'
    from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
    from /usr/local/bundle/gems/oidc_provider-0.2.0/app/controllers/oidc_provider/application_controller.rb:3:in `<class:ApplicationController>'
```

**Comment by willtcarey** [comment]
Hmm, typically in Rails the "concerns" namespace is not counted. So in `app/controllers/oidc_provider/concerns/authentication.rb` the concern is specified as `OidcProvider::Concerns::Authentication` which seems to be working some of the time at least? But it may be that it's supposed to be `OidcProvider::Authentication` and included that way?

**Comment by nathancolgate** [comment]
This struck me again while trying to test for routes:

```
nathan@garibaldi:~/rails/aecom-cola$ dip bash
bash-4.2# bundle exec rails-route-checker
bundler: failed to load command: rails-route-checker (/usr/local/bundle/bin/rails-route-checker)
NameError: uninitialized constant Concerns::Authentication
```

**Comment by nathancolgate** [comment]
I was able to temporarily get around it by commenting out the gem and related configuration.

**Comment by willtcarey** [comment]
Ah I did the exact same thing when I was trying to generate an ERD of COLA the other day.
